WELCOME_MESSAGE = 'Welcome!'
VARIANCE = 'variance'
SKEWNESS = 'skewness'
CURTOSIS = 'curtosis'
ENTROPY = 'entropy'
CSV_FILE = '.csv file'
METHOD_GET = 'GET'
METHOD_POST = 'POST'
READ_BYTE_MODE = 'rb'
MODEL_FILE_NAME = 'classifier.pkl'
DEFAULT_ENDPOINT = '/'
PREDICT_ENDPOINT = '/predict'
PREDICT_FILE_ENDPOINT = '/predict_file'
CLASS_1 = 'class 1'
CLASS_0 = 'class 0'
MAIN = '__main__'
FLASK_APP_PORT = 8080
LOCAL_PORT = 5000
DEFAULT_PATH = 'http://localhost:{0}/apidocs/'.format(LOCAL_PORT)
LOCALHOST = '0.0.0.0'

